input_data_path: 'data/raw/heart.csv'
output_model_path: 'models/logreg_model.pkl'
metric_path: 'models/logreg_metrics.json'
logs_path: 'logs/logs.txt'
splitting_params:
  val_size: 0.1
  random_state: 100
train_params:
  model_type: 'LogisticRegression'
  model_params:
    # model_params may contain any supported params of model_type
    random_state: 42
feature_params:
  categorical_features:
    - 'sex'
    - 'cp'
    - 'restecg'
    - 'exang'
  numerical_features:
    - 'age'
    - 'trestbps'
    - 'thalach'
    - 'oldpeak'
    - 'slope'
    - 'ca'
    - 'thal'
  features_to_drop:
    - 'fbs'
    - 'chol'
  target_col: 'target'
