input_model_path: 'models/rfc_model.pkl'
input_data_path: 'data/to_predict/heart_without_target.csv'
output_data_path: 'data/to_predict/prediction.csv'
logs_path: 'logs/logs.txt'
feature_params:
  categorical_features:
    - 'sex'
    - 'cp'
    - 'fbs'
    - 'restecg'
    - 'exang'
  numerical_features:
    - 'age'
    - 'trestbps'
    - 'chol'
    - 'thalach'
    - 'oldpeak'
    - 'slope'
    - 'ca'
    - 'thal'