apiVersion: v1
kind: Pod
metadata:
  name: online-inference-ill
  labels:
    app: online-inference-ill
spec:
  containers:
    - image: lkudrenok/online-inference-ill:v1
      name: online-inference-ill
      ports:
        - containerPort: 8000
      readinessProbe:
        httpGet:
          path: /health/
          port: 8000
        initialDelaySeconds: 20
        periodSeconds: 3
      livenessProbe:
        httpGet:
          path: /health/
          port: 8000
        initialDelaySeconds: 50
        periodSeconds: 10
