name: hw1_pylint_pytest

on:
  push:
    paths:
    - 'ml_project/**'
    - '.github/workflows/hw1_pylint_pytest.yml'

jobs:
  build:
    runs-on: windows-latest

    steps:

    - name: Clone repo
      uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      working-directory: ./ml_project
      run: |
        pip install -r requirements.txt

    - name: Run linter
      working-directory: ./ml_project
      run: |
        pylint run_pipeline.py ml_project --exit-zero

    - name: Run tests
      working-directory: ./ml_project
      run: |
        pytest
